package ca.bc.gov.nrs.hrs;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;

/**
 * Application-level constants used across the backend.
 *
 * <p>This utility class groups a small set of public string constants that are
 * referenced in multiple places (for example, HTTP header names and special identifiers). The class
 * is non-instantiable (private no-args constructor generated by Lombok's
 * {@link NoArgsConstructor}).</p>
 *
 * @since 1.0.0
 */
@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class BackendConstants {

  /**
   * HTTP header used to carry the total number of items in a paged response. Commonly set on
   * responses that return a page of results so clients can determine the overall total irrespective
   * of page size.
   */
  public static final String X_TOTAL_COUNT = "X-Total-Count";

  /**
   * Sentinel value used to indicate the absence of a client identifier. Some legacy systems or
   * integration points require a non-null value; this constant represents that 'no client' state.
   */
  public static final String NOCLIENT = "NOCLIENT";

}
