-- No foreign keys found
-- DDL migration for ORG_UNIT (DBeaver style)
CREATE TABLE ORG_UNIT (
    ORG_UNIT_NO NUMBER(10,0) NOT NULL,
    ORG_UNIT_CODE VARCHAR2(6) NOT NULL,
    ORG_UNIT_NAME VARCHAR2(100) NOT NULL,
    LOCATION_CODE VARCHAR2(3) NOT NULL,
    AREA_CODE VARCHAR2(3) NOT NULL,
    TELEPHONE_NO VARCHAR2(7) NOT NULL,
    ORG_LEVEL_CODE VARCHAR2(1) NOT NULL,
    OFFICE_NAME_CODE VARCHAR2(2) NOT NULL,
    ROLLUP_REGION_NO NUMBER(10,0) NOT NULL,
    ROLLUP_REGION_CODE VARCHAR2(6) NOT NULL,
    ROLLUP_DIST_NO NUMBER(10,0) NOT NULL,
    ROLLUP_DIST_CODE VARCHAR2(6) NOT NULL,
    EFFECTIVE_DATE DATE NOT NULL,
    EXPIRY_DATE DATE NOT NULL,
    UPDATE_TIMESTAMP DATE
);

-- Explicit CHECK constraints
ALTER TABLE ORG_UNIT ADD CONSTRAINT SYS_C0019614 CHECK (ORG_UNIT_NO IS NOT NULL);
ALTER TABLE ORG_UNIT ADD CONSTRAINT SYS_C0019615 CHECK (ORG_UNIT_CODE IS NOT NULL);
ALTER TABLE ORG_UNIT ADD CONSTRAINT SYS_C0019616 CHECK (ORG_UNIT_NAME IS NOT NULL);
ALTER TABLE ORG_UNIT ADD CONSTRAINT SYS_C0019617 CHECK (LOCATION_CODE IS NOT NULL);
ALTER TABLE ORG_UNIT ADD CONSTRAINT SYS_C0019618 CHECK (AREA_CODE IS NOT NULL);
ALTER TABLE ORG_UNIT ADD CONSTRAINT SYS_C0019619 CHECK (TELEPHONE_NO IS NOT NULL);
ALTER TABLE ORG_UNIT ADD CONSTRAINT SYS_C0019620 CHECK (ORG_LEVEL_CODE IS NOT NULL);
ALTER TABLE ORG_UNIT ADD CONSTRAINT SYS_C0019621 CHECK (OFFICE_NAME_CODE IS NOT NULL);
ALTER TABLE ORG_UNIT ADD CONSTRAINT SYS_C0019622 CHECK (ROLLUP_REGION_NO IS NOT NULL);
ALTER TABLE ORG_UNIT ADD CONSTRAINT SYS_C0019623 CHECK (ROLLUP_REGION_CODE IS NOT NULL);
ALTER TABLE ORG_UNIT ADD CONSTRAINT SYS_C0019624 CHECK (ROLLUP_DIST_NO IS NOT NULL);
ALTER TABLE ORG_UNIT ADD CONSTRAINT SYS_C0019625 CHECK (ROLLUP_DIST_CODE IS NOT NULL);
ALTER TABLE ORG_UNIT ADD CONSTRAINT SYS_C0019626 CHECK (EFFECTIVE_DATE IS NOT NULL);
ALTER TABLE ORG_UNIT ADD CONSTRAINT SYS_C0019627 CHECK (EXPIRY_DATE IS NOT NULL);

-- Primary Key
ALTER TABLE ORG_UNIT ADD CONSTRAINT ORG_UNIT_PK PRIMARY KEY (ORG_UNIT_NO);

-- Unique Indexes
CREATE UNIQUE INDEX I8$_ORG_UNIT ON ORG_UNIT (ORG_UNIT_CODE);
CREATE UNIQUE INDEX I9$_ORG_UNIT ON ORG_UNIT (ORG_UNIT_NAME);
CREATE UNIQUE INDEX I1$_ORG_UNIT ON ORG_UNIT (LOCATION_CODE);
CREATE UNIQUE INDEX I2$_ORG_UNIT ON ORG_UNIT (AREA_CODE);
CREATE UNIQUE INDEX I3$_ORG_UNIT ON ORG_UNIT (TELEPHONE_NO);
CREATE UNIQUE INDEX I4$_ORG_UNIT ON ORG_UNIT (ROLLUP_REGION_CODE);

-- Non-unique Indexes
CREATE INDEX I5$_ORG_UNIT ON ORG_UNIT (ROLLUP_DIST_CODE);
CREATE INDEX I6$_ORG_UNIT ON ORG_UNIT (UPDATE_TIMESTAMP);
CREATE INDEX I7$_ORG_UNIT ON ORG_UNIT (ORG_LEVEL_CODE);

